Fix compile errors on Visual Studio 2019
1>------ Build started: Project: xtensor-zarr-gdal, Configuration: RelWithDebInfo x64 ------
1>xtensor-zarr-gdal.cpp
...(some warnings)...
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(127,21): error C2440: '<function-style-cast>': cannot convert from 'ghc::filesystem::path' to 'std::string'
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(127,21): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(127,21): error C2512: 'std::runtime_error': no appropriate default constructor available
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(127,21): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(212,41): error C2440: 'initializing': cannot convert from 'const ghc::filesystem::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(212,41): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(247,41): error C2440: 'initializing': cannot convert from 'const ghc::filesystem::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_file_system_store.hpp(247,41): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\Libs\xtensor-zarr\src\xtensor-zarr-gdal.cpp(8,84): warning C4251: 'xt::xchunked_array_factory<xt::xzarr_file_system_store>::m_builders': class 'std::map<std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t),std::less<StringType>,std::allocator<std::pair<const std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t)>>>' needs to have dll-interface to be used by clients of class 'xt::xchunked_array_factory<xt::xzarr_file_system_store>'
1>        with
1>        [
1>            store_type=xt::xzarr_file_system_store,
1>            T=size_t,
1>            StringType=std::string
1>        ]
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_chunked_array.hpp(95): message : see declaration of 'std::map<std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t),std::less<StringType>,std::allocator<std::pair<const std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t)>>>'
1>        with
1>        [
1>            store_type=xt::xzarr_file_system_store,
1>            T=size_t,
1>            StringType=std::string
1>        ]
1>C:\Libs\xtensor-zarr\src\xtensor-zarr-gdal.cpp(13,77): warning C4251: 'xt::xchunked_array_factory<xt::xzarr_gdal_store>::m_builders': class 'std::map<std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t),std::less<StringType>,std::allocator<std::pair<const std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t)>>>' needs to have dll-interface to be used by clients of class 'xt::xchunked_array_factory<xt::xzarr_gdal_store>'
1>        with
1>        [
1>            store_type=xt::xzarr_gdal_store,
1>            T=size_t,
1>            StringType=std::string
1>        ]
1>C:\Libs\xtensor-zarr\include\xtensor-zarr\xzarr_chunked_array.hpp(95): message : see declaration of 'std::map<std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t),std::less<StringType>,std::allocator<std::pair<const std::string,xt::zarray (__cdecl *)(store_type &,const std::string &,char,std::vector<T,std::allocator<T>> &,std::vector<T,std::allocator<T>> &,const std::string &,char,const nlohmann::json &,char,nlohmann::json &,size_t,const nlohmann::json &,size_t)>>>'
1>        with
1>        [
1>            store_type=xt::xzarr_gdal_store,
1>            T=size_t,
1>            StringType=std::string
1>        ]
1>Done building project "xtensor-zarr-gdal.vcxproj" -- FAILED.